apiVersion: v1
kind: Service
metadata:
  name: kanyerest-service
  namespace: misiano-dev
spec:
  selector:
    app: kanyerest
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: kanye-port
    protocol: TCP